version: 2
jobs:
  build:
    working_directory: ./
    environment:
        REPO: https://github.com/enkidevs/prototype_challenge
    steps:
      - run:
          name: Running tests
          command: npm test
